export enum Permission {
  GET_USER = 'GET_USER',
  LIST_USERS = 'LIST_USERS',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  GET_COMPANY = 'GET_COMPANY',
  LIST_COMPANIES = 'LIST_COMPANIES',
  CREATE_COMPANY = 'CREATE_COMPANY',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  DELETE_COMPANY = 'DELETE_COMPANY',
}
